from pathlib import Path
import json,pandas as pd, matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1]; weekly=pd.read_csv(ROOT/'data/processed/weekly_demand.csv',parse_dates=['week']); sku=pd.read_csv(ROOT/'data/processed/sku_master.csv'); risk=pd.read_csv(ROOT/'outputs/risk_scores.csv'); audit=json.loads((ROOT/'data/processed/pipeline_audit.json').read_text())
fig=ROOT/'reports/figures';fig.mkdir(parents=True,exist_ok=True)
weekly.groupby('week').demand.sum().plot(figsize=(10,4),title='Total Weekly Demand');plt.tight_layout();plt.savefig(fig/'weekly_demand.png',dpi=150);plt.close()
top=weekly.groupby('sku_id').demand.sum().nlargest(10).sort_values();top.plot.barh(figsize=(8,4),title='Top 10 SKUs by Units');plt.tight_layout();plt.savefig(fig/'top_skus.png',dpi=150);plt.close()
wk=weekly.merge(sku[['sku_id','category']],on='sku_id',how='left').groupby('category').demand.sum().sort_values();wk.plot.barh(figsize=(8,4),title='Units by Category');plt.tight_layout();plt.savefig(fig/'category_demand.png',dpi=150);plt.close()
topsku=weekly.groupby('sku_id').demand.sum().idxmax(); topsku_units=weekly.groupby('sku_id').demand.sum().max(); slow=weekly.groupby('sku_id').demand.sum().nsmallest(1); risk_counts=risk.recommended_action.value_counts();
mapping='''| FORESIGHT field | Actual dataset field | Status |\n|---|---|---|\n| SKU | `sales_transactions.sku_id` | Available |\n| Date | `sales_transactions.date` | Available |\n| Units sold | `sales_transactions.quantity` | Available |\n| Revenue | `sales_transactions.total_value` | Available |\n| Price | `sales_transactions.unit_price`; `sku_master.unit_price` | Available |\n| Category | `sku_master.category` | Available |\n| Promotion | `promo_id`, `discount_pct`; `promotions.csv` | Available |\n| Inventory | `inventory_snapshot.stock_on_hand`, `reorder_point`, `safety_stock` | Available (snapshot, not history) |\n| On order | — | Not available |\n'''
(ROOT/'reports/data_quality_report.md').write_text(f'''# Data Quality Report\n\nSource: clean `sales_transactions.csv`\n\n- Shape: {audit['rows']:,} rows × 11 columns\n- Date range: {audit['date_range'][0]} to {audit['date_range'][1]}\n- Unique SKUs: {audit['unique_skus']:,}\n- Missing values in selected pipeline columns: {audit['missing_values']}\n- Duplicate rows: not calculated across the 10M-row raw file to preserve memory; the pipeline aggregates valid date/SKU/quantity records.\n\n## Data Mapping\n\n{mapping}\n''',encoding='utf-8')
(ROOT/'reports/eda_report.md').write_text(f'''# Actual Data Insights\n\n1. The clean transaction source covers **{audit['rows']:,} transactions** across **{audit['unique_skus']:,} SKUs** from **{audit['date_range'][0]} to {audit['date_range'][1]}**.\n2. Total observed volume is **{audit['total_units']:,.0f} units** and total recorded revenue is **₹{audit['total_revenue']:,.0f}**.\n3. **{topsku}** is the highest-volume SKU at **{topsku_units:,.0f} units**; the slowest SKU is **{slow.index[0]}** at **{slow.iloc[0]:,.0f} units**.\n4. Inventory actions based on the supplied snapshot: **{risk_counts.get('REORDER NOW',0):,} reorder**, **{risk_counts.get('MARKDOWN / CLEAR',0):,} markdown**, **{risk_counts.get('WATCH / VOLATILE',0):,} watch**, and **{risk_counts.get('HEALTHY',0):,} healthy** SKUs.\n\nCharts: `reports/figures/weekly_demand.png`, `top_skus.png`, `category_demand.png`.\n''',encoding='utf-8')
(ROOT/'reports/executive_readout.md').write_text('''# Executive Readout\n\nFORESIGHT forecasts weekly SKU demand and converts the eight-week outlook into transparent inventory actions. Forecast quality is reported honestly in `model_results.csv`; the production selection uses the lower validation WAPE. Inventory is a supplied static snapshot, so the project does not claim inventory history or on-order visibility. Sales at risk and capital locked are estimates derived from the snapshot, unit price/cost, forecast, and a documented two-week lead-time assumption.\n''',encoding='utf-8')
